// ui_kits/designer/presets.js — example architectures users can load

window.PRESETS = [
  {
    id: "blank",
    label: "Blank canvas",
    description: "Start from scratch",
    layers: [],
    connections: [],
  },
  {
    id: "lstm-classifier",
    label: "LSTM classifier",
    description: "Input → LSTM → Dense → Softmax",
    layers: [
      { id: "p1l1", name: "Input", type: "input", units: 64, activation: "Linear", neuronType: "linear",
        position: { x: 80, y: 110 }, dropout: 0,
        inputConfig: { sampleRate: 1000, windowWidth: 100, stride: 50, dataStructure: "Channels x Features", channels: 1, features: 64 } },
      { id: "p1l2", name: "LSTM", type: "lstm", units: 128, activation: "Tanh", neuronType: "lstm-cell",
        position: { x: 260, y: 110 }, dropout: 0.1, returnSequences: true, bidirectional: false },
      { id: "p1l3", name: "Dense", type: "mlp", units: 64, activation: "ReLU", neuronType: "relu",
        position: { x: 440, y: 110 }, dropout: 0.2 },
      { id: "p1l4", name: "Output", type: "output", units: 10, activation: "Softmax", neuronType: "sigmoid",
        position: { x: 620, y: 110 }, dropout: 0,
        outputConfig: { outputType: "probabilities", channels: 1, numClasses: 10, outputStructure: "Channels x Features" } },
    ],
    connections: [
      { id: "p1c1", fromLayerId: "p1l1", toLayerId: "p1l2", type: "forward" },
      { id: "p1c2", fromLayerId: "p1l2", toLayerId: "p1l3", type: "forward" },
      { id: "p1c3", fromLayerId: "p1l3", toLayerId: "p1l4", type: "forward" },
      { id: "p1c4", fromLayerId: "p1l2", toLayerId: "p1l2", type: "recurrent" },
    ],
  },
  {
    id: "transformer",
    label: "Transformer encoder",
    description: "Input → Transformer × 2 → Dense → Output",
    layers: [
      { id: "p2l1", name: "Input", type: "input", units: 64, activation: "Linear", neuronType: "linear",
        position: { x: 60, y: 110 }, dropout: 0,
        inputConfig: { sampleRate: 1000, windowWidth: 256, stride: 64, dataStructure: "Channels x Features", channels: 1, features: 512 } },
      { id: "p2l2", name: "Attention 1", type: "transformer", units: 512, activation: "GELU", neuronType: "gated",
        position: { x: 220, y: 110 }, dropout: 0.1, numHeads: 8, embeddingDim: 512 },
      { id: "p2l3", name: "Attention 2", type: "transformer", units: 512, activation: "GELU", neuronType: "gated",
        position: { x: 380, y: 110 }, dropout: 0.1, numHeads: 8, embeddingDim: 512 },
      { id: "p2l4", name: "Dense", type: "mlp", units: 128, activation: "GELU", neuronType: "relu",
        position: { x: 540, y: 110 }, dropout: 0.2 },
      { id: "p2l5", name: "Output", type: "output", units: 100, activation: "Softmax", neuronType: "sigmoid",
        position: { x: 700, y: 110 }, dropout: 0,
        outputConfig: { outputType: "probabilities", channels: 1, numClasses: 100, outputStructure: "Channels x Features" } },
    ],
    connections: [
      { id: "p2c1", fromLayerId: "p2l1", toLayerId: "p2l2", type: "forward" },
      { id: "p2c2", fromLayerId: "p2l2", toLayerId: "p2l3", type: "forward" },
      { id: "p2c3", fromLayerId: "p2l3", toLayerId: "p2l4", type: "forward" },
      { id: "p2c4", fromLayerId: "p2l4", toLayerId: "p2l5", type: "forward" },
      { id: "p2c5", fromLayerId: "p2l1", toLayerId: "p2l3", type: "skip" },
    ],
  },
  {
    id: "cnn-pipeline",
    label: "CNN pipeline",
    description: "Input → CNN × 3 → Dense → Output",
    layers: [
      { id: "p3l1", name: "Input", type: "input", units: 3, activation: "Linear", neuronType: "linear",
        position: { x: 40, y: 110 }, dropout: 0,
        inputConfig: { sampleRate: 1, windowWidth: 224, stride: 1, dataStructure: "Channels x Features", channels: 3, features: 224 } },
      { id: "p3l2", name: "Conv 1", type: "cnn", units: 32, activation: "ReLU", neuronType: "relu",
        position: { x: 180, y: 110 }, dropout: 0, numFilters: 32, kernelSize: 3, stride: 1 },
      { id: "p3l3", name: "Conv 2", type: "cnn", units: 64, activation: "ReLU", neuronType: "relu",
        position: { x: 320, y: 110 }, dropout: 0, numFilters: 64, kernelSize: 3, stride: 1 },
      { id: "p3l4", name: "Conv 3", type: "cnn", units: 128, activation: "ReLU", neuronType: "relu",
        position: { x: 460, y: 110 }, dropout: 0, numFilters: 128, kernelSize: 3, stride: 2 },
      { id: "p3l5", name: "Dense", type: "mlp", units: 256, activation: "ReLU", neuronType: "relu",
        position: { x: 600, y: 110 }, dropout: 0.3 },
      { id: "p3l6", name: "Output", type: "output", units: 1000, activation: "Softmax", neuronType: "sigmoid",
        position: { x: 740, y: 110 }, dropout: 0,
        outputConfig: { outputType: "probabilities", channels: 1, numClasses: 1000, outputStructure: "Channels x Features" } },
    ],
    connections: [
      { id: "p3c1", fromLayerId: "p3l1", toLayerId: "p3l2", type: "forward" },
      { id: "p3c2", fromLayerId: "p3l2", toLayerId: "p3l3", type: "forward" },
      { id: "p3c3", fromLayerId: "p3l3", toLayerId: "p3l4", type: "forward" },
      { id: "p3c4", fromLayerId: "p3l4", toLayerId: "p3l5", type: "forward" },
      { id: "p3c5", fromLayerId: "p3l5", toLayerId: "p3l6", type: "forward" },
    ],
  },
  {
    id: "autoencoder",
    label: "RNN autoencoder",
    description: "Encoder ↔ Decoder with bottleneck",
    layers: [
      { id: "p4l1", name: "Input", type: "input", units: 64, activation: "Linear", neuronType: "linear",
        position: { x: 40, y: 110 }, dropout: 0,
        inputConfig: { sampleRate: 1000, windowWidth: 100, stride: 50, dataStructure: "Channels x Features", channels: 1, features: 64 } },
      { id: "p4l2", name: "Encoder", type: "lstm", units: 64, activation: "Tanh", neuronType: "lstm-cell",
        position: { x: 200, y: 110 }, dropout: 0.1, returnSequences: false, bidirectional: false },
      { id: "p4l3", name: "Bottleneck", type: "mlp", units: 16, activation: "Linear", neuronType: "linear",
        position: { x: 360, y: 110 }, dropout: 0 },
      { id: "p4l4", name: "Decoder", type: "lstm", units: 64, activation: "Tanh", neuronType: "lstm-cell",
        position: { x: 520, y: 110 }, dropout: 0.1, returnSequences: true, bidirectional: false },
      { id: "p4l5", name: "Output", type: "output", units: 64, activation: "Linear", neuronType: "linear",
        position: { x: 680, y: 110 }, dropout: 0,
        outputConfig: { outputType: "regression", channels: 1, outputStructure: "Channels x Features" } },
    ],
    connections: [
      { id: "p4c1", fromLayerId: "p4l1", toLayerId: "p4l2", type: "forward" },
      { id: "p4c2", fromLayerId: "p4l2", toLayerId: "p4l3", type: "forward" },
      { id: "p4c3", fromLayerId: "p4l3", toLayerId: "p4l4", type: "forward" },
      { id: "p4c4", fromLayerId: "p4l4", toLayerId: "p4l5", type: "forward" },
      { id: "p4c5", fromLayerId: "p4l2", toLayerId: "p4l2", type: "recurrent" },
      { id: "p4c6", fromLayerId: "p4l4", toLayerId: "p4l4", type: "recurrent" },
    ],
  },
  {
    id: "mpf-gesture",
    label: "MPF gesture classifier (AR-LSTM → MLP)",
    description: "Recursive LSTM rollout concatenated with x_t, classified by a 2-layer MLP",
    figureCaption: "Figure. The MPF feature window x_t is forwarded through a one-layer LSTM (128 units, Tanh, dropout 0.05) trained as a one-step recursive predictor. The hidden state is projected through a fully-connected forecast head back into feature space, then iterated H = 10 windows (≈ 200 ms at the 20 ms MPF stride). The concatenated context [x_t ; x̂_{t+1} ; … ; x̂_{t+H}] is classified by a 2-layer MLP (512 → 512, ReLU, dropout 0.5) with a softmax over gesture classes. Cross-entropy loss; Adam, initial LR 1e-3 dropped ×0.5 every 40 epochs; early stopping (patience 20, 15 % blocked validation / 15 % blocked test).",
    figure: {
      title: "MPF gesture classifier (AR-LSTM → MLP)",
      showLegend: true, showGroupOutline: true, showLayerCaptions: true,
      showShapes: true, showEdgeLabels: false, variableNames: false,
    },
    layers: [
      { id: "mpf-input", name: "MPF window", type: "input", units: 32, activation: "Linear", neuronType: "linear",
        position: { x: 56, y: 58 }, dropout: 0,
        annotation: "x_t  ∈  ℝ^{32}",
        inputConfig: { sampleRate: 2048, windowWidth: 200, stride: 40, dataStructure: "Channels*Features x 1", channels: 8, features: 24 } },
      { id: "mpf-lstm", name: "LSTM", type: "lstm", units: 128, activation: "Tanh", neuronType: "lstm-cell",
        position: { x: 213, y: 60 }, dropout: 0.05,
        returnSequences: true, bidirectional: false,
        predictionHorizon: 10, contextWindows: 64, forecastMode: "recursive",
        annotation: "H = 10, ctx = 64" },
      { id: "mpf-forecast", name: "Forecast FC", type: "mlp", units: 32, activation: "Linear", neuronType: "linear",
        position: { x: 329, y: 61 }, dropout: 0,
        annotation: "x̂_{t+k}  ∈  ℝ^{32}" },
      { id: "mpf-concat", name: "Concat", type: "concat", units: 352, activation: "Linear", neuronType: "concat",
        position: { x: 482, y: 62 }, dropout: 0,
        annotation: "[x_t ; x̂_{t+1..t+H}]" },
      { id: "mpf-dense1", name: "FC 1", type: "mlp", units: 512, activation: "ReLU", neuronType: "relu",
        position: { x: 624, y: 61 }, dropout: 0.5 },
      { id: "mpf-dense2", name: "FC 2", type: "mlp", units: 512, activation: "ReLU", neuronType: "relu",
        position: { x: 750, y: 61 }, dropout: 0.5 },
      { id: "mpf-output", name: "Gesture", type: "output", units: 8, activation: "Softmax", neuronType: "sigmoid",
        position: { x: 872, y: 62 }, dropout: 0,
        annotation: "ŷ  ∈  ℝ^{C}",
        outputConfig: { outputType: "probabilities", channels: 1, numClasses: 8, outputStructure: "Channels x Features" } },
    ],
    connections: [
      { id: "mpf-c1", fromLayerId: "mpf-input",    toLayerId: "mpf-lstm",     type: "forward",   transform: "none" },
      { id: "mpf-c2", fromLayerId: "mpf-lstm",     toLayerId: "mpf-forecast", type: "forward",   transform: "linear", annotation: "h_t → ŷ" },
      { id: "mpf-c3", fromLayerId: "mpf-lstm",     toLayerId: "mpf-lstm",     type: "recurrent", annotation: "h_{t−1}, c_{t−1}" },
      { id: "mpf-c4", fromLayerId: "mpf-forecast", toLayerId: "mpf-concat",   type: "forward",   transform: "none",   annotation: "x̂_{t+1..t+H}" },
      { id: "mpf-c5", fromLayerId: "mpf-input",    toLayerId: "mpf-concat",   type: "skip",      transform: "none",   annotation: "x_t" },
      { id: "mpf-c6", fromLayerId: "mpf-concat",   toLayerId: "mpf-dense1",   type: "forward",   transform: "affine" },
      { id: "mpf-c7", fromLayerId: "mpf-dense1",   toLayerId: "mpf-dense2",   type: "forward",   transform: "affine" },
      { id: "mpf-c8", fromLayerId: "mpf-dense2",   toLayerId: "mpf-output",   type: "forward",   transform: "affine" },
    ],
    groups: [
      { id: "mpf-g1", label: "AR-LSTM predictor (200 ms horizon)", layerIds: ["mpf-lstm", "mpf-forecast"], paletteId: "rose" },
      { id: "mpf-g2", label: "Gesture MLP classifier",              layerIds: ["mpf-concat", "mpf-dense1", "mpf-dense2"], paletteId: "blue" },
    ],
    annotations: [
      { id: "mpf-a1", kind: "text",    x: 164,  y: 218,  text: "x_t",          italic: true },
      { id: "mpf-a2", kind: "text",    x: 469,  y: 221,  text: "x̂_{t+1..t+H}", italic: true },
      { id: "mpf-a3", kind: "text",    x: 1100, y: 180,  text: "ŷ",            italic: true },
      { id: "mpf-a4", kind: "bracket", x1: 178, y1: 383, x2: 432, y2: 386, label: "feature predictor", flip: false },
      { id: "mpf-a5", kind: "bracket", x1: 462, y1: 379, x2: 862, y2: 379, label: "classifier head",   flip: false },
    ],
  },
];
